# https://www.gitpod.io/docs
# https://www.gitpod.io/docs/references/gitpod-yml
# Commands to start on workspace startup
tasks:
  - name: Dependencies
    init: |
      pipx install mockintosh
      pipx inject mockintosh markupsafe==2.0.1
      cd ./single-threaded
      ./mvnw -B dependency:go-offline package -DskipTests
      mysql -e "show databases;"
      mysql -e "create database if not exists singlethreadeddb;"
      mysql -e "show databases;"
      task dbbootstraping
      cd ..
#- init: ./spring-batch-projects/mvnw -B dependency:go-offline package -DskipTests
#  command: java -jar target/*.jar
#  name: Run SingleThreaded app

image:
  file: .gitpod.Dockerfile

# Define which path Gitpod considers the project’s workspace directory, relative to /workspace.
# workspaceLocation: "./single-threaded"

# exposed ports
ports:
  - name: Web
    port: 8080
    onOpen: ignore
  - name: Database
    port: 3306
    onOpen: notify
    visibility: private

# Configure the VS Code editor.
vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

# Define the integration between Gitpod and JetBrains IDEs.
jetbrains:
  intellij:
    vmoptions: "-Xms2048m -Xmx2048m -XX:ReservedCodeCacheSize=1024m -Didea.connection.timeout=3600000"
    # Find a page of the required plugin.
    # Select the Versions tab.
    # Click any version to copy the pluginId (short name such as org.rust.lang) of the plugin you want to install.
    plugins:
      - com.haulmont.jpab
      - zielu.gittoolbox # GitToolBox
      - izhangzhihao.rainbow.brackets # Rainbow Brackets
      - lechuck.intellij-plugin.task # Taskfile
      - cn.yiiguxing.plugin.translate # Translation
      - com.intellij.grazie.pro # Grazie pro
      - de.endrullis.idea.postfixtemplates # Custom Postfix Templates
      - ru.adelf.idea.dotenv # .env files support
      - String Manipulation # String Manipulation
      - com.ultrahob.zerolength.plugin # Zero Width Characters locator
      - com.intellij.javaee.batch # Jakarta EE: Batch Applications
      - com.intellij.spring.batch # Spring Batch
    prebuilds:
      version: stable
