tasks:
- init: ./mvnw -B dependency:go-offline package -DskipTests
  command: java -jar target/*.jar
  name: Run SingleThreaded app

image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    vmoptions: "-Xmx2g"
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both