# https://www.gitpod.io/docs
# https://www.gitpod.io/docs/references/gitpod-yml
# Commands to start on workspace startup
#tasks:
#- init: ./spring-batch-projects/mvnw -B dependency:go-offline package -DskipTests
#  command: java -jar target/*.jar
#  name: Run SingleThreaded app

image:
  file: .gitpod.Dockerfile

# Define which path Gitpod considers the project’s workspace directory, relative to /workspace.
workspaceLocation: "./single-threaded"

# exposed ports
ports:
  - name: Web
    port: 8080
    onOpen: ignore

# Configure the VS Code editor.
vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

# Define the integration between Gitpod and JetBrains IDEs.
jetbrains:
  intellij:
    vmoptions: "-Xmx2g"
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both