version: '3.7'
services:
  db:
    image: mysql:5.7.33
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASS}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      # Host:Container
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mydbdata:/var/lib/mysql
volumes:
  mydbdata: