version: '3'
tasks:
  hello-world:
    cmds:
      - echo "Hello world"
  up-db:
    cmds:
      - docker compose up -d db
  build:
    cmds:
      - docker build -t fronzec/single-threaded:latest .
  down:
    cmds:
      - docker-compose down --remove-orphans
  up:
    deps: [ down,build ]
    cmds:
      - docker-compose up