version: '3'
tasks:
  hello:
    cmds:
      - echo "Hello world, task works ok!!!"
  setup-envs:
    cmds:
      - cp env.example.txt .env
    # test existence of files
    preconditions:
      - sh: "! test -f .env"
        msg: "==========> .env file already exists, their values will be used"


  up-db:
    cmds:
      - docker compose up -d db
  up-service:
    cmds:
      - docker compose up -d single-threaded
  build:
    cmds:
      - docker build -t fronzec/single-threaded:latest .
  down:
    cmds:
      - docker-compose down --remove-orphans
  up:
    deps: [ down,build ]
    cmds:
      - docker-compose up